import "./globals.css";
import type { Metadata } from "next";
import { Inter, Salsa, Unbounded } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const salsa = Salsa({ weight: "400", subsets: ["latin"] });
const unbounded = Unbounded({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={unbounded.className}>{props.children}</body>
    </html>
  );
}
