import "./globals.css";
import type {Metadata} from "next";
import {Unbounded} from "next/font/google";
import DarkTheme from "./components/dark-theme";

const unbounded = Unbounded({subsets: ["latin"]});
export const metadata: Metadata = {
  title: "Red Social",
  description: "Generated by create next app",
};

export default function RootLayout(props: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <DarkTheme />

      <body className={unbounded.className}>
        {props.children}
        <div id="modal-root" />
      </body>
    </html>
  );
}
